const STRING_INPUT = 0
const TEXTAREA_INPUT = 1
const INTEGER_INPUT = 2
const FLOAT_INPUT = 3
const DROPDROWN_MULTIPLECHOISES_INPUT = 4
const BOOLEAN_INPUT = 5
const DATETIME_INPUT = 6
const DATE_INPUT = 7
const TIME_INPUT = 8
const DROPDROWN_SINGLECHOISE_INPUT = 8
const CHECKBOX_INPUT = 10
const RADIO_INPUT = 11
const SLIDER_FROMZERO_INPUT = 12
const SLIDER_RANGE_INPUT = 13

export {
    STRING_INPUT,
    TEXTAREA_INPUT,
    INTEGER_INPUT,
    FLOAT_INPUT,
    BOOLEAN_INPUT,
    DATETIME_INPUT,
    DATE_INPUT,
    TIME_INPUT,
    DROPDROWN_SINGLECHOISE_INPUT,
    DROPDROWN_MULTIPLECHOISES_INPUT,
    CHECKBOX_INPUT,
    RADIO_INPUT,
    SLIDER_FROMZERO_INPUT,
    SLIDER_RANGE_INPUT
}